name: Github Actions Tutorial - Greeting

on: [push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: "ls command"
        run: ls -a
      - name: "pwd command"
        run: pwd
